version: '3.1'
services:
  test:
    image: postgres
    ports:
      - '7777:7777'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
      - POSTGRES_HOST_AUTH_METHOD=trust
